# Generated by Django 3.2.6 on 2022-10-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_player_age', models.IntegerField(default=0)),
                ('description', models.TextField(default="Let's add later")),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('playing_time', models.IntegerField(default=0)),
                ('min_players_number', models.IntegerField(default=1)),
                ('max_players_number', models.IntegerField(default=100)),
                ('price', models.IntegerField(default=0)),
                ('rating_from_the_store', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Board Game',
                'verbose_name_plural': 'Board Games',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Without category', max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Category name',
                'verbose_name_plural': 'Category names',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.boardgames')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='boardgames',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='game_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
