# Generated by Django 3.2.6 on 2021-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_boardgames_category_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgames',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgames',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
    ]
