# Generated by Django 3.2.6 on 2021-08-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210829_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
