# Generated by Django 3.2.6 on 2021-09-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_boardgames_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='max_players_number',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='min_players_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='playing_time',
            field=models.IntegerField(default=0),
        ),
    ]
