# Generated by Django 3.2.6 on 2021-09-04 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210904_1204'),
        ('catalog', '0007_rename_category_name_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=240)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='catalog.boardgames')),
            ],
        ),
    ]
