# Generated by Django 3.2.6 on 2021-09-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
