# Generated by Django 3.2.6 on 2021-09-08 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='likes',
            field=models.ManyToManyField(related_name='game_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
