# Generated by Django 3.2.6 on 2021-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_boardgames_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='rating_from_the_store',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=1),
        ),
    ]
