# Generated by Django 3.2.6 on 2021-09-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_boardgames_rating_from_the_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgames',
            old_name='name_of_game',
            new_name='name',
        ),
    ]
