# Generated by Django 3.2.6 on 2021-09-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_rename_name_of_game_boardgames_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgames',
            old_name='game_description',
            new_name='description',
        ),
    ]
